// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK9kmGkTnPeUAQ8C2glAuiXVYRTZB-SXY',
    appId: '1:114182687338:web:44fc8043d52dc7e1a01813',
    messagingSenderId: '114182687338',
    projectId: 'blacksea-4a970',
    authDomain: 'blacksea-4a970.firebaseapp.com',
    storageBucket: 'blacksea-4a970.appspot.com',
    measurementId: 'G-F3EJE5H4XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyLIviER8A9ha44VNG1If2icEzNQV4SPU',
    appId: '1:114182687338:android:b5f9b8c81da79b45a01813',
    messagingSenderId: '114182687338',
    projectId: 'blacksea-4a970',
    storageBucket: 'blacksea-4a970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6uwqQcEF7_4vr5nfv6StvsyJdea9wtfY',
    appId: '1:114182687338:ios:73328c69b4b73c9ca01813',
    messagingSenderId: '114182687338',
    projectId: 'blacksea-4a970',
    storageBucket: 'blacksea-4a970.appspot.com',
    iosBundleId: 'com.mananbhimjiyani.blackseaproduct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6uwqQcEF7_4vr5nfv6StvsyJdea9wtfY',
    appId: '1:114182687338:ios:b4fe230cd154f67aa01813',
    messagingSenderId: '114182687338',
    projectId: 'blacksea-4a970',
    storageBucket: 'blacksea-4a970.appspot.com',
    iosBundleId: 'com.mananbhimjiyani.blackseaproduct.RunnerTests',
  );
}
