import '../Schemas/product.dart';

List<Product> generateDummyProducts() {
  return [
    Product(
      productID: '1',
      productName: 'Dummy Product 1',
      brand: 'Dummy Brand 1',
      barCode: '123456789',
      category: 'Dummy Category 1',
      unit: 'grams',
      bulkPack: 'Bulk Pack 1',
      unitConversion: 'Conversion 1',
      eachUnitContains: '100',
      productImage1: '',
      productImage2: '',
      productImage3: '',
      specification: 'Specification 1',
      reorderLevel: '10',
      requiredQuantity: 0,
    ),
    Product(
      productID: '2',
      productName: 'Dummy Product 2',
      brand: 'Dummy Brand 2',
      barCode: '987654321',
      category: 'Dummy Category 2',
      unit: 'ml',
      bulkPack: 'Bulk Pack 2',
      unitConversion: 'Conversion 2',
      eachUnitContains: '200',
      productImage1: '',
      productImage2: '',
      productImage3: '',
      specification: 'Specification 2',
      reorderLevel: '15',
      requiredQuantity: 0,
    ),
    Product(
      productID: '3',
      productName: 'Dummy Product 3',
      brand: 'Dummy Brand 3',
      barCode: '135792468',
      category: 'Dummy Category 3',
      unit: 'pieces',
      bulkPack: 'Bulk Pack 3',
      unitConversion: 'Conversion 3',
      eachUnitContains: '50',
      productImage1: '',
      productImage2: '',
      productImage3: '',
      specification: 'Specification 3',
      reorderLevel: '20',
      requiredQuantity: 0,
    ),
    Product(
      productID: '4',
      productName: 'Dummy Product 4',
      brand: 'Dummy Brand 4',
      barCode: '246801357',
      category: 'Dummy Category 4',
      unit: 'pieces',
      bulkPack: 'Bulk Pack 4',
      unitConversion: 'Conversion 4',
      eachUnitContains: '75',
      productImage1: '',
      productImage2: '',
      productImage3: '',
      specification: 'Specification 4',
      reorderLevel: '25',
      requiredQuantity: 0,
    ),
    Product(
      productID: '5',
      productName: 'Dummy Product 5',
      brand: 'Dummy Brand 5',
      barCode: '369258147',
      category: 'Dummy Category 5',
      unit: 'pieces',
      bulkPack: 'Bulk Pack 5',
      unitConversion: 'Conversion 5',
      eachUnitContains: '80',
      productImage1: '',
      productImage2: '',
      productImage3: '',
      specification: 'Specification 5',
      reorderLevel: '30',
      requiredQuantity: 0,
    ),
    Product(
      productID: '6',
      productName: 'Dummy Product 6',
      brand: 'Dummy Brand 6',
      barCode: '4815162342',
      category: 'Dummy Category 6',
      unit: 'liters',
      bulkPack: 'Bulk Pack 6',
      unitConversion: 'Conversion 6',
      eachUnitContains: '500',
      productImage1: '',
      productImage2: '',
      productImage3: '',
      specification: 'Specification 6',
      reorderLevel: '35',
      requiredQuantity: 0,
    ),
    // Add more dummy products as needed
  ];
}
