import '../Schemas/requisition.dart';
import '../Schemas/requisitionLineItem.dart';

List<Requisition> generateDummyRequisitions() {
  return [
    Requisition(
      reqID: 1,
      locationID: 101,
      reqDate: DateTime(2023, 10, 15),
      user: 'John Doe',
      lineItems: [
        RequisitionLineItem(productName: 'Product A', quantity: 10),
        RequisitionLineItem(productName: 'Product B', quantity: 5),
      ],
      userRemarks: 'Urgent request',
      approver: 'Jane Smith',
      approverRemarks: 'Approved',
      status: 'WIP',
      procurementRemarks: 'Waiting for delivery',
      procurementCompletedOn: null,
      closureDate: null,
      powerAppsId: 'PA12345',
    ),
    Requisition(
      reqID: 2,
      locationID: 102,
      reqDate: DateTime(2023, 10, 16),
      user: 'Alice Johnson',
      lineItems: [
        RequisitionLineItem(productName: 'Product C', quantity: 8),
        RequisitionLineItem(productName: 'Product D', quantity: 3),
      ],
      userRemarks: 'Standard request',
      approver: 'Bob Brown',
      approverRemarks: 'Approved',
      status: 'Order Placed',
      procurementRemarks: 'Delivered on time',
      procurementCompletedOn: DateTime(2023, 10, 18),
      closureDate: DateTime(2023, 10, 20),
      powerAppsId: 'PA67890',
    ),
    Requisition(
      reqID: 3,
      locationID: 103,
      reqDate: DateTime(2023, 10, 18),
      user: 'Emily White',
      lineItems: [
        RequisitionLineItem(productName: 'Product E', quantity: 15),
        RequisitionLineItem(productName: 'Product F', quantity: 7),
      ],
      userRemarks: 'High priority request',
      approver: 'Chris Green',
      approverRemarks: 'Approved',
      status: 'Out for Delivery',
      procurementRemarks: 'Processing order',
      procurementCompletedOn: null,
      closureDate: null,
      powerAppsId: 'PA24680',
    ),
    Requisition(
      reqID: 4,
      locationID: 104,
      reqDate: DateTime(2023, 10, 20),
      user: 'David Black',
      lineItems: [
        RequisitionLineItem(productName: 'Product G', quantity: 20),
        RequisitionLineItem(productName: 'Product H', quantity: 10),
      ],
      userRemarks: 'Regular request',
      approver: 'Ella Brown',
      approverRemarks: 'Approved',
      status: 'Delivered',
      procurementRemarks: 'Items delivered',
      procurementCompletedOn: DateTime(2023, 10, 22),
      closureDate: DateTime(2023, 10, 25),
      powerAppsId: 'PA13579',
    ),
    Requisition(
      reqID: 5,
      locationID: 105,
      reqDate: DateTime(2023, 10, 22),
      user: 'Sarah Lee',
      lineItems: [
        RequisitionLineItem(productName: 'Product I', quantity: 12),
        RequisitionLineItem(productName: 'Product J', quantity: 6),
      ],
      userRemarks: 'Emergency request',
      approver: 'Michael Taylor',
      approverRemarks: 'Not important',
      status: 'On Hold',
      procurementRemarks: 'Processing order',
      procurementCompletedOn: null,
      closureDate: null,
      powerAppsId: 'PA98765',
    ),
    Requisition(
      reqID: 6,
      locationID: 106,
      reqDate: DateTime(2023, 10, 25),
      user: 'Emma Davis',
      lineItems: [
        RequisitionLineItem(productName: 'Product K', quantity: 18),
        RequisitionLineItem(productName: 'Product L', quantity: 9),
      ],
      userRemarks: 'Routine request',
      approver: 'Oliver Martinez',
      approverRemarks: 'Approved',
      status: 'On Hold',
      procurementRemarks: 'Order in progress',
      procurementCompletedOn: null,
      closureDate: null,
      powerAppsId: 'PA54321',
    ),
    Requisition(
      reqID: 7,
      locationID: 107,
      reqDate: DateTime(2023, 10, 28),
      user: 'Sophia Garcia',
      lineItems: [
        RequisitionLineItem(productName: 'Product M', quantity: 25),
        RequisitionLineItem(productName: 'Product N', quantity: 15),
      ],
      userRemarks: 'Critical request',
      approver: 'William Rodriguez',
      approverRemarks: 'Approved',
      status: 'Pending',
      procurementRemarks: 'Items on order',
      procurementCompletedOn: null,
      closureDate: null,
      powerAppsId: 'PA24681',
    ),
    Requisition(
      reqID: 8,
      locationID: 108,
      reqDate: DateTime(2023, 11, 2),
      user: 'David Wilson',
      lineItems: [
        RequisitionLineItem(productName: 'Product O', quantity: 20),
        RequisitionLineItem(productName: 'Product P', quantity: 12),
      ],
      userRemarks: 'Urgent restock',
      approver: 'Elizabeth Anderson',
      approverRemarks: 'Approved',
      status: 'Pending',
      procurementRemarks: 'Order being processed',
      procurementCompletedOn: null,
      closureDate: null,
      powerAppsId: 'PA13579',
    ),
    Requisition(
      reqID: 9,
      locationID: 109,
      reqDate: DateTime(2023, 11, 5),
      user: 'James Brown',
      lineItems: [
        RequisitionLineItem(productName: 'Product Q', quantity: 15),
        RequisitionLineItem(productName: 'Product R', quantity: 8),
      ],
      userRemarks: 'Regular request',
      approver: 'Ava Martinez',
      approverRemarks: 'Approved',
      status: 'Pending',
      procurementRemarks: 'Order awaiting confirmation',
      procurementCompletedOn: null,
      closureDate: null,
      powerAppsId: 'PA80246',
    ),
    Requisition(
      reqID: 10,
      locationID: 110,
      reqDate: DateTime(2023, 11, 8),
      user: 'Emily Taylor',
      lineItems: [
        RequisitionLineItem(productName: 'Product S', quantity: 30),
        RequisitionLineItem(productName: 'Product T', quantity: 20),
      ],
      userRemarks: 'Large order',
      approver: 'Matthew Thomas',
      approverRemarks: 'Approved',
      status: 'Pending',
      procurementRemarks: 'Order processing',
      procurementCompletedOn: null,
      closureDate: null,
      powerAppsId: 'PA36985',
    ),
  ];
}
